version: "2"
volumes:
  postgres:
    driver: "local"
  memcached:
    driver: "local"

services:

    postgresql:
        build: ./docker/postgresql
        ports:
            - "5432:5432"
        volumes:
            - ./:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: oasisqe
            POSTGRES_USER: oasisqe
            POSTGRES_PASSWORD: oasisqe

    oasisqe:
        build: ./src
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - postgresql
            - memcached
        
    memcached:
          build: ./docker/memcached
          volumes:
            - ./:/var/lib/memcached
          ports:
            - "11211:11211"

