version: "2"
volumes:
  postgres:
    driver: "local"
  memcached:
    driver: "local"

services:

    postgresql:
        build: ./docker/postgresql
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: oasisqe
            POSTGRES_USER: oasisqe
            POSTGRES_PASSWORD: oasisqe

    oasisqe:
        build: ./src
        ports:
            - "8000:8000"
        depends_on:
            - postgresql
            - memcached
        
    memcached:
          build: ./docker/memcached
          ports:
            - "11211:11211"

