#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

""" Given an oa_export.zip file, import the contained questions into a topic.

    import_topic test_questions.zip TOPIC_ID
"""

import sys
import os

# we should be SOMETHING/bin/import_topic, find APPDIR
# and add "SOMETHING/src" to our path

APPDIR = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "src")
sys.path.append(APPDIR)

from oasis.lib import Users, External, Topics


if len(sys.argv) < 2:
    print "Usage: "
    print "    import_topic <filename.zip> [TOPIC_ID]"
    sys.exit(1)

filename = sys.argv[1]
topicid = int(sys.argv[2])
uid = Users.uid_by_uname('admin')

topic = Topics.get_topic(topicid)

data = open(filename).read()
External.import_qts_from_zip(data, topicid)
