#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

""" Reset the OASIS admin password. If given an argument, set the password to that, otherwise
    generate a random one.
"""

import sys
import os

# we should be SOMETHING/bin/reset_admin_password, find APPDIR
# and add "SOMETHING/src" to our path

APPDIR = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "src")
sys.path.append(APPDIR)

from oasis.lib import Users, OaConfig, Users2, Permissions


if len(sys.argv) > 1:
    passwd = sys.argv[1]
else:
    passwd = Users.gen_confirm_code()

uid = Users.uid_by_uname('admin')
if not uid:
    uid = Users.create(uname="admin",
                       passwd="NOLOGIN",
                       email=OaConfig.email,
                       givenname="Admin",
                       familyname="Account",
                       acctstatus=1,
                       studentid="",
                       source="local",
                       confirm_code="",
                       confirm=True)
Users2.set_password(uid, passwd)

Permissions.add_perm(uid, 0, 1)  # superuser
print "The new admin password is:  ", passwd
