#!/usr/bin/python3
# -*- coding: utf-8 -*-

""" Reset the OASIS admin password. If given an argument, set the password to that, otherwise
    generate a random one.
"""

import sys
import os

# find installed copy of OASIS
UPTWO=os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
APPDIR=None

if "OASISLIB" in os.environ:
   APPDIR = os.environ["OASISLIB"]
elif os.path.isdir("/opt/oasisqe/3.9/src/oasis"):
   APPDIR = "/opt/oasisqe/3.9/src"
elif os.path.isdir("/opt/oasisqe/3.9/oasis"):
   APPDIR = "/opt/oasisqe/3.9"
elif os.path.isdir("%s/%s"%(UPTWO,"/oasis")):
   APPDIR = UPTWO
elif os.path.isdir("%s/%s"%(UPTWO,"/src/oasis")):
   APPDIR = UPTWO+"/src"

if not APPDIR:
    print("Unable to find installed OASIS code, normally at /opt/oasisqe/3.9/src")
    print("You can specify it in the OASIS lib environment variable on the commandline: ")
    print("          OASISLIB=/opt/oasisqe/3.9/src oasisdb")
    exit(1)

print(("using copy of OASIS installed at %s" % APPDIR))

sys.path.append(APPDIR)

from oasis.lib import Users, OaConfig, Users2, Permissions


if len(sys.argv) > 1:
    passwd = sys.argv[1]
else:
    passwd = Users.gen_confirm_code()

uid = Users.uid_by_uname('admin')
if not uid:
    uid = Users.create(uname="admin",
                       passwd="NOLOGIN",
                       email=OaConfig.email,
                       givenname="Admin",
                       familyname="Account",
                       acctstatus=1,
                       studentid="",
                       source="local",
                       confirm_code="",
                       confirm=True)
Users2.set_password(uid, passwd)

Permissions.add_perm(uid, 0, 1)  # superuser
print(("The new admin password is:  ", passwd))
